import { Nunito } from "next/font/google";
import "./styles/global.css";
import { Header } from "@/widgets/Header";
import { ConfigProvider } from "antd";
import { config } from "./providers/AntdConfig";

const nunito = Nunito({
  subsets: ["cyrillic"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "RePizza",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.variable}>
        <ConfigProvider theme={config}>
          <Header />
          <main className="main">{children}</main>
        </ConfigProvider>
      </body>
    </html>
  );
}
